### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by adamyi** [Chester-P/sqli-tools#1]
It doesn't work with python 2.

**Comment by Chester-P** [comment]
2to3 boolean_fuzz.py
Problem solved :)

**Comment by adamyi** [comment]
Nah that doesn't solve the problem.

It would be nice if you could update your script to support running it using both python 2.x and 3 :-)

**Comment by Chester-P** [comment]
I've got a better one:
simply do
```
sudo rm `which python`
sudo ln -s `which python3` /usr/bin/python
```
XD
